http://localhost:3005/users
###
http://localhost:3005/users/1

###
POST http://localhost:3005/users
Content-Type: application/json

{
    "bio": "Cookie Developer",
    "username": "johndoe2"
}

###
PUT http://localhost:3005/users/1
Content-Type: application/json

{
    "bio": "Jane Bose girl",
    "username": "jany"
}